<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Default suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Default test(failed)">
    <classes>
      <class name="com.api.testing.RestAssuredTest.AppTest">
        <methods>
          <include name="testGetBookWithInvalidId"/>
          <include name="testLoginWithIncorrectPassword"/>
          <include name="setup"/>
          <include name="testDeleteBook"/>
          <include name="testCreateBook"/>
          <include name="testUnauthorizedAccess"/>
          <include name="testUserLogin"/>
          <include name="logTestResult"/>
          <include name="testInvalidLogin"/>
          <include name="tearDown"/>
          <include name="testCreateMultipleBooks" invocation-numbers="0 1 2"/>
          <include name="testGetBookById"/>
          <include name="testUserSignup"/>
          <include name="testSignupWithExistingEmail"/>
        </methods>
      </class> <!-- com.api.testing.RestAssuredTest.AppTest -->
    </classes>
  </test> <!-- Default test(failed) -->
</suite> <!-- Failed suite [Default suite] -->
